apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy
    component: frontend
  name: oauth2-proxy
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
      component: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oauth2-proxy
        component: frontend
    spec:
      containers:
      - name: oauth2-proxy
        image: a5huynh/oauth2_proxy:2.2
        imagePullPolicy: IfNotPresent
        args:
        - --cookie-domain=.n10.io
        - --cookie-expire=36h
        - --cookie-name=_auth_proxy
        - --cookie-refresh=1h
        - --email-domain=nicolerenee.io
        - --http-address=0.0.0.0:4180
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: oauth2-proxy
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: oauth2-proxy
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: cookie-secret
              name: oauth2-proxy
        ports:
        - containerPort: 4180
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: http
        readinessProbe:
          httpGet:
            path: /ping
            port: http
