apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
    component: frontend
  name: oauth2-proxy
  namespace: media
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: oauth2-proxy
    component: frontend
  type: ClusterIP
