---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: snmp-exporter
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: snmp-exporter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-snmp-exporter
    version: 0.0.5
  valuesFrom:
  - secretKeyRef:
      name: snmp-exporter-helm-values
      namespace: monitoring
      key: values.yaml
  values:
    nameOverride: snmp-exporter
    fullnameOverride: snmp-exporter
    image:
      tag: v0.18.0
    replicas: 2
    serviceMonitor:
      enabled: false