apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault01-nzbget
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    iqn: iqn.2016-01.io.n10:vault01.appdata-nzbget.cdab998267
    targetPortal: 172.20.1.5
    lun: 0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget
  namespace: media
spec:
  volumeName: vault01-nzbget
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
