---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-farnsworth-data
  namespace: warehouse20
  labels:
    app: plex
    instance: farnsworth
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: rook-ceph-block
