---
apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   flux.weave.works/tag.fluxcloud: glob:v2.*
  #   flux.weave.works/automated: 'true'
  labels:
    app: varkan
    app.kubernetes.io/name: varken
    app.kubernetes.io/part-of: varken
  name: varken
  namespace: warehouse20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varken
  template:
    metadata:
      labels:
        app: varken
    spec:
      containers:
      - name: varken
        image: boerderij/varken:1.6.6
        env:
          - name: PGID
            value: "911"
          - name: PUID
            value: "911"
          - name: TZ
            value: America/Denver
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 256Mi
        # securityContext:
        #   runAsUser: 1024
        #   runAsGroup: 100
        volumeMounts:
        - mountPath: /config
          name: data
      volumes:
      - name: data
        nfs:
          path: /mnt/ssd01/k8s/warehouse20/varken
          server: 172.20.1.10
