---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: vault
  chart:
    repository: https://helm.releases.hashicorp.com
    name: vault
    version: 0.6.0
  values:
    server:
      extraEnvironmentVars:
        GOOGLE_REGION: global
        GOOGLE_PROJECT: freckle-tech
        GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/credentials.json

      extraVolumes:
        - type: 'secret'
          name: 'kms-creds'

      ha:
        enabled: true
        raft:
          enabled: true
          config: |
            ui = true

            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }

            storage "raft" {
              path = "/vault/data"
            }

            service_registration "kubernetes" {}

            seal "gcpckms" {
              credentials = "/vault/userconfig/kms-creds/credentials.json"
              project     = "freckle-tech"
              region      = "global"
              key_ring    = "den1-k8s01-vault"
              crypto_key  = "vault"
            }