apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-store01
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: warehouse20
    name: media-store01
  nfs:
    path: /mnt/store01/warehouse20/media/
    server: 172.25.2.4
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-store01
  namespace: warehouse20
spec:
  volumeName: media-store01
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1Ti
