apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault01-radarr
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    iqn: iqn.2016-01.io.n10:vault01.appdata-radarr.cdab998267
    targetPortal: vault.infra.n10.io
    lun: 0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: media
spec:
  volumeName: vault01-radarr
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
