apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
    component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: http
      port: 80
      protocol: TCP
  selector:
    app: radarr
