apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    iqn: iqn.2016-01.io.n10:vault01.k8s-alertmanager.cdab998267
    targetPortal: 172.20.1.5
    lun: 0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  volumeName: vault-alertmanager
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
