apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tx-att
  namespace: monitoring
  annotations:
    flux.weave.works/tag.fluxcloud: glob:master-*
    flux.weave.works/automated: 'true'
  labels:
    app: speedtest
    server: texas-att
spec:
  replicas: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: speedtest
      server: texas-att
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: speedtest
        server: texas-att
    spec:
      containers:
      - image: quay.io/nicolerenee/speedtest-exporter:master-7863961
        imagePullPolicy: IfNotPresent
        name: speedtest
        ports:
        - containerPort: 9104
          protocol: TCP
        env:
        - name: SERVERS
          value: "5023"
        - name: DURATION
          value: "300"
