apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: speedtest-den
  namespace: monitoring
  annotations:
    flux.weave.works/tag.fluxcloud: glob:master-*
    flux.weave.works/automated: 'true'
  labels:
    app: speedtest
    server: denver-centurylink
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: speedtest
      server: denver-centurylink
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: speedtest
        server: denver-centurylink
    spec:
      containers:
      - image: quay.io/nicolerenee/speedtest-exporter:master-7863961
        imagePullPolicy: IfNotPresent
        name: speedtest
        ports:
        - containerPort: 9104
          protocol: TCP
        env:
        - name: SERVERS
          value: "8862"
        - name: DURATION
          value: "120"
