---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: warehouse20
  labels:
    app: sonarr
spec:
  ports:
    - name: http
      targetPort: http
      port: 8989
      protocol: TCP
  selector:
    app: sonarr
