---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mysql
  namespace: db
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: mariadb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: mariadb
    version: 7.6.1
  valuesFrom:
  - secretKeyRef:
      name: mariadb-values
      namespace: db
      key: values.yaml
  values:
    global:
      storageClass: rook-ceph-block
    master:
      persistence:
        size: 16Gi
    slave:
      persistence:
        size: 16Gi
    rootUser:
      forcePassword: true
      injectSecretAsVolume: true
    db:
      forcePassword: true
      injectSecretAsVolume: true
    replication:
      forcePassword: true
      injectSecretAsVolume: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true