---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-data
  namespace: warehouse20
  labels:
    app: nzbget
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
