apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-owen-01
  namespace: minecraft
  labels:
    app: minecraft
    owner: owen
    instance: "01"
spec:
  serviceName: mc-owen-01
  selector:
    matchLabels:
      app: minecraft
      owner: owen
      instance: "01"
  template:
    metadata:
      labels:
        app: minecraft
        owner: owen
        instance: "01"
    spec:
      automountServiceAccountToken: false
      containers:
      - name: minecraft
        image: itzg/minecraft-bedrock-server:latest
        imagePullPolicy: Always
        tty: true
        stdin: true
        env:
        - name: EULA
          value: "TRUE"
        - name: SERVER_NAME
          value: "mc-owen-01 - Private"
        - name: GAMEMODE
          value: creative
        - name: DIFFICULTY
          value: normal
        - name: MAX_PLAYERS
          value: "5"
        - name: WHITE_LIST
          value: "true"
        - name: DEFAULT_PLAYER_PERMISSION_LEVEL
          value: visitor
        - name: LEVEL_TYPE
          value: default
        - name: ALLOW_CHEATS
          value: "true"
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 2048Mi
            cpu: 2000m
        ports:
        - name: minecraft
          containerPort: 19132
          protocol: UDP
        volumeMounts:
        - name: datadir
          mountPath: /data
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: mc-owen-01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-owen-01
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem

---
apiVersion: v1
kind: Service
metadata:
  name: mc-owen-01
  namespace: minecraft
  annotations:
    metallb.universe.tf/address-pool: public
    metallb.universe.tf/allow-shared-ip: kids-minecraft
spec:
  ports:
  - port: 19155
    targetPort: minecraft
    protocol: UDP
    name: minecraft
  selector:
    app: minecraft
    owner: owen
    instance: "01"
  type: LoadBalancer
  externalTrafficPolicy: Cluster
