---
apiVersion: v1
kind: Service
metadata:
  name: plex-farnsworth
  namespace: warehouse20
  labels:
    app: plex
    instance: farnsworth
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: https
      targetPort: https
      port: 32400
      protocol: TCP
  selector:
    app: plex
    instance: farnsworth
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-farnsworth
  namespace: warehouse20
  labels:
    app: plex
    instance: farnsworth
spec:
  serviceName: plex-farnsworth
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: plex
      instance: farnsworth
  template:
    metadata:
      labels:
        app: plex
        instance: farnsworth
    spec:
      automountServiceAccountToken: false
      containers:
        - name: farnsworth
          image: plexinc/pms-docker:1.19.3.2843-e3c1f7bcd
          env:
          - name: ADVERTISE_IP
            value: "https://farnsworth.warehouse20.com/"
          - name: PLEX_UID
            value: "943"
          - name: PLEX_GID
            value: "943"
          - name: TZ
            value: "Etc/UTC"
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /identity
              port: https
          readinessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /identity
              port: https
          ports:
            - containerPort: 32400
              name: https
          resources:
            requests:
              cpu: 1000m
              gpu.intel.com/i915: 1
              memory: "2Gi"
            limits:
              cpu: 4000m
              gpu.intel.com/i915: 1
              memory: "8Gi"
          volumeMounts:
          - mountPath: /config
            name: config
            subPath: config
          - mountPath: /transcode
            name: tmp-storage
          - mountPath: /tmp
            name: tmp-storage
          - mountPath: /mnt/media/store01
            name: store01-media
      volumes:
        - name: config
          persistentVolumeClaim:
              claimName: plex-farnsworth-data
        - name: tmp-storage
          emptyDir: {}
        - name: store01-media
          persistentVolumeClaim:
            claimName: media-store01
