kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: cloudflare-api
  namespace: cert-manager

spec:
  template:
    metadata:
      name: cloudflare-api
      namespace: cert-manager
  encryptedData:
    apikey: AgBc9lhvdlqDjBELEOD6vnd6CdTRYtbgyP9J9HJlK0MY8rh2XGSR1hjLfGyIdq07HAkmV3hu2G/R7XY8WqrOXu9XtR0wB8OJd67+OXdVjRL8x7CfDI6n/rJywY5jqNdoRMVtX6hpiMg9GnagNl9I6oJqc1ru9ImSkZPJba0ypob0JrbV2v1h4b3gFasOSpebLFCRpzw3XmS/3pRKTWCi/QZJHrIfyyZL6JkCv+kXGr/QZw/nUc9RR038edUN7AfW10jbFgqXoBEH7fNEXppPKv8pdAbeIouCSl3AJW2qVe+TbrPPz7neQJD/JfMEaU7Y0OFcbzAcdgh1GcxIxYNQUlpebCcifiOy8mzf9FqhmjcMK0OYo+/D2ii7FA+mBtMrun/R47oc3jGG+J7MNnTbJBxfOiIa/GhLKrhN5htkVctlzeuSuZOqh2Ep4mior3U4O9PG5d4J6p23nt+QmlRwHarU6Pr5uusC223qMQ7KQMjrePxVkNqjywHWObfyExjaxcq5yMPPsyV9IamEZny37S6WQZYsVFq0lIblc6Yzi1P0n+B9H6io1CYIjxWXgOJ9sDZYgAC/R9w4ZVjrY8BsyU2rZ9Nuv+Zt/2aE8MdrxRIrSvm0qMxkZFU2AF7yoeQw0TewBgRqjZRxUyc/hgHN527gC2/KFwQeiWOom6BeNLmcy8Ya9vWAKnL0luAV0nlaQzbvCQtMMnmUj64dyQnkP2vf0C6oEDhHDRDjEimV7pAHI3LE1ilA
