apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: n10-infra
spec:
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  selector:
    app: coredns
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: dns-udp
  namespace: n10-infra
  annotations:
    metallb.universe.tf/address-pool: internal
    metallb.universe.tf/allow-shared-ip: coredns-resolver
spec:
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns
  selector:
    app: coredns
  type: LoadBalancer
  loadBalancerIP: 172.20.240.5
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  name: dns-tcp
  namespace: n10-infra
  annotations:
    metallb.universe.tf/address-pool: internal
    metallb.universe.tf/allow-shared-ip: coredns-resolver
spec:
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns
  selector:
    app: coredns
  type: LoadBalancer
  loadBalancerIP: 172.20.240.5
  externalTrafficPolicy: Local
