---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: metrics-server
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metrics-server
    version: 4.1.13
  values:
    extraArgs:
      kubelet-insecure-tls: true
      kubelet-preferred-address-types: InternalIP