---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: warehouse20
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: http
      port: 7878
      protocol: TCP
    - name: monitoring
      targetPort: monitoring
      port: 9707
  selector:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
