---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-gooery-data
  namespace: warehouse20
  labels:
    app: tautulli
    instance: gooery
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
