apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 172.20.1.1
      peer-asn: 65101
      my-asn: 65102
    address-pools:
    - name: internal
      protocol: bgp
      addresses:
      - 172.20.240.0/22
