apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-data
  namespace: warehouse20
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 5Gi
