---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: snmp-exporter
  name: snmp-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: http
    port: 9116
    protocol: TCP
  selector:
    app: snmp-exporter
