---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: fluxcloud
  namespace: flux
spec:
  encryptedData:
    slack_url: AgCgrM8fOInsknpJgQ095QGJVIA6DGGp/5w6OsYwSKz4YaPOcvUoi64OhYTf08aiMl3cg3QS1Mi/hdg9Y8MfZv/1QBwR5bo+hmq7v73T/KjgpIjCYrMoSQAC2JusGxO0BcAYo20xpnJ5p0dxHYa1cwJdFsSXwc908ntN36FyARdlNYB+UQEhyTLbjezrVbH10nkopxHR7GUE5R+8n7Xc0w7Hla93X3eSFuSJU1sBGIbfnh81Avoh56A6G0EUgcEFhzuAZ1BS0IvdN6qPYlZzXZ7Yy/HCtR2NwF7UWkyHTukPib393dCnZ5ObVBk2xRvmPQu4OlnVCrY6zZNC6+7DltaOTjNzk6fDi+gz6DY3pKnG0Ke5tA8MSQUgBdemIK5WTWB48zBipPj/OpsF2dD53VhFPK6S8PVAgRY7BG/ZzR+rpYEkReYWUs0A4GtoAdQ3zrRGxW8JOVGInBnf4Cb+719jS3Jj2tUmEr6kD/TOrpJm7MS8WEhQRUwJAPt3bnOLtHcys/QHbOpbZKLmtHIQu1rj/JqDzC+zt2P/rbYYpGzZ7oQOge28AgFZNTOqVtGACdkJhhV/uA+wW0ivANCU1xTbvlYONJeJFahxEJWSvbv7TVqbssGuvelJKpVg/jP2u4XfugyGZGqpAqNDL5leOnV7z97zaybzDmW8/ZY3TZBcc9hXIHNaprNsqmSnilc3Hs41ZBBdFB/0DCA6ptoXIoue513x/bMmyOmj3r+MW8LAn/fsEehxAzCTOy51A+5O84LW9rumWWmL4KAR9UKDxUOQj2LCc76qXqm8J/F4mg==
