---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
  namespace: flux
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3031
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxcloud
  namespace: flux
  annotations:
    flux.weave.works/tag.fluxcloud: glob:master-*
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      containers:
      - name: fluxcloud
        image: justinbarrick/fluxcloud:master-89f5fec
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3031
        env:
        - name: SLACK_URL
          value: "https://hooks.slack.com/services/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"
        - name: SLACK_CHANNEL
          value: "#kubernetes"
        - name: SLACK_USERNAME
          value: Flux Deployer
        - name: SLACK_ICON_EMOJI
          value: ":heart:"
        - name: GITHUB_URL
          value: "https://github.com/nicolerenee/k8s-state/"
