---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: fluxcloud
  namespace: flux
spec:
  encryptedData:
    slack_url: AgCrhKNTh0SPvhTOmtmuB1WP8theFCm3+Yjy9nOyORF2UTbKdI5InTsAPpM3HxS07WWk3yC03KsFnZgHwaPHAGjK0NEuGzQT7HkHJTXr8lnDyIYxWXonJ5NjGYR91PRrUVSLqIHRn1xpsjtUUNs3+Fz8SDAfKPBFp6ccpDx7wv9gYqeHys//u8e3gUBK12Xff7gNtYuUDrjOO25weliCqfFEDvhgB0YsxWm3yml8Yl1AqdCP5KCM19hybTy0EWJNCWjBbCVxMrbGaxjj9znnbzzwZnYmISSw5mR6R86qdUKgCx5tMk6cBHFpx+0XGpC5eZVm5gZG6RAyfh28KCSqqYH7AzAM16yF6leVyre1zU/9ovriDYTxC7ENikdCIC2uwrs+Sj8h8a9xBwemC6NaMuq+fitb+yUcZEGuchL2rYD7oGgQFfrJoNyBefckd4yC+69YI/THG831jdaZtmmBnToLQLWWFzxP3MZOHWoMgC6FlN9XjF9P20AARlchutpH+HCaWjFjNX1cx3Nka6mJw+QoO1x0GQvGzgXfuOpcIM12lGK/FjngXLkl+vOZyYetTGIhhYQCXhGTdo0OuxbQENipp9bLgtNAwVnMxw6ZK1vPe+yW7JI6+s2vwtBBHKsDIhAYK/cVhkpArPS7c5pyrY+96IzVxDNlahwvTKxd8q4gmMMZkQLUFjatMRE6yWmqLGE7sQ3RNpUNcMZyIpJGuAcoNiH6gtxrsf4hTXNIa3ycrvCCl/nn9m1yRBDZLN2NHauVkzkoCu/9p/T/mKkVqx/akqLQ1eeC+Ob0AOMWWw==
