apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/media/movies
    server: 172.20.1.5
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies
  namespace: media
spec:
  volumeName: media-movies
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1Ti
