apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: rook-prometheus
    role: alert-rules
  name: kured-rules
  namespace: kube-system
spec:
  groups:
  - name: kured.rules
    rules:
    - alert: RebootRequired
      annotations:
        identifier: "{{ $labels.node }}"
        summary: "Reboot Required for {{ $labels.node }}"
        description: "requires a reboot, and the reboot daemon has failed to do so for 6 hours."
      expr: |
        max(kured_reboot_required) != 0
      for: 6h
      labels:
        severity: warning