---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: kured
  chart:
    repository: https://weaveworks.github.io/kured
    name: kured
    version: 2.0.3
  valuesFrom:
  - secretKeyRef:
      name: kured-secrets
      namespace: kube-system
      key: values.yaml
  values:
    updateStrategy: RollingUpdate
    configuration:
      prometheusUrl: http://prometheus-operator-prometheus.monitoring.svc.cluster.local:9090
      alertFilterRegexp: ^RebootRequired$
      slackUsername: "kured - den1-k8s01"
    metrics:
      create: true