---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~1.
spec:
  releaseName: vault-secrets-operator
  chart:
    repository: https://ricoberger.github.io/helm-charts
    name: vault-secrets-operator
    version: 1.7.1
  values:
    deploymentStrategy:
      type: Recreate
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 200Mi
    vault:
      address: "http://vault.vault:8200"
      authMethod: kubernetes
      kubernetesPath: auth/kubernetes
      kubernetesRole: vault-secrets-operator
      reconciliationTime: "180"