apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: prometheus-operator-prometheus-scrape-config
  namespace: monitoring
spec:
  keys:
    - additional-scrape-configs.yaml
  path: kube-secrets/monitoring/prometheus/additional-scrap-config
  type: Opaque