---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prom
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: kube-prometheus
    version: 4.2.2
  values:
    global:
      storageClass: rook-ceph-block
    operator:
      logLevel: error
    prometheus:
      additionalScrapeConfigsExternal:
        enabled: true
        name: prometheus-operator-prometheus-scrape-config
        key: additional-scrape-configs.yaml
      logLevel: error
      scrapeInterval: 30s
      replicaCount: 1
      retention: 90d
      persistence:
        enabled: true
        size: 100Gi
    alertmanager:
      logLevel: error
      replicaCount: 2
      persistence:
        enabled: true
        size: 5Gi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - name: alerts.den1.freckle.tech
          path: /
        tls:
        - hosts:
          - alerts.den1.freckle.tech
          secretName: alertmanager-tls
      config:
        receivers:
          - name: slack
            slack_configs:
            - channel: '#alerts'
              send_resolved: true
              title: '{{ template "custom_title" . }}'
              text: '{{ template "custom_slack_message" . }}'
