---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-public
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: nginx-ingress-controller
    version: 5.3.22
  values:
    fullnameOverride: nginx-ingress
    config:
      use-forwarded-headers: "true"
    publishService:
      enabled: true
    metrics:
      enabled: true
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/address-pool: public
      loadBalancerIP: 72.18.145.241