---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: unifi
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: unifi
    version: 0.10.0
  values:
    image:
      repository: nicolerenee/unifi
      tag: 5.14.9
    guiService:
      type: ClusterIP
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 72.18.145.242
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-controller
        metallb.universe.tf/address-pool: public
    stunService:
      type: LoadBalancer
      loadBalancerIP: 72.18.145.242
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/allow-shared-ip: unifi-controller
        metallb.universe.tf/address-pool: public
    discoveryService:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
      - unifi.freckle.tech
      tls:
      - hosts:
        - unifi.freckle.tech
        secretName: unifi-tls
    persistence:
      size: 40Gi
      storageClass: rook-ceph-block
