---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: traktarr
    app.kubernetes.io/instance: traktarr
  name: traktarr
  namespace: warehouse20
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traktarr
      app.kubernetes.io/instance: traktarr
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traktarr
        app.kubernetes.io/instance: traktarr
    spec:
      automountServiceAccountToken: false
      containers:
      - name: traktarr
        image: cloudb0x/traktarr:latest
        imagePullPolicy: Always
        args:
          - --config
          - /config/config.json
          - run
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        resources:
          requests:
            cpu: "10m"
            memory: 64Mi
          limits:
            cpu: "1000m"
            memory: 512Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 100
        volumeMounts:
        - mountPath: /config
          name: config
          subPath: config
      volumes:
      - name: config
        persistentVolumeClaim:
            claimName: traktarr-data