---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traktarr-data
  namespace: warehouse20
  labels:
    app.kubernetes.io/name: traktarr
    app.kubernetes.io/instance: traktarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
