---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: metallb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metallb
    version: 0.1.12
  values:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    configInline:
      peers:
        # core01a
        - peer-address: 172.26.3.2
          peer-asn: 64567
          my-asn: 64590
        # core01b
        - peer-address: 172.26.3.3
          peer-asn: 64567
          my-asn: 64590
      address-pools:
      - name: internal
        protocol: bgp
        auto-assign: true
        addresses:
        - 172.26.10.0/24
      - name: public
        protocol: bgp
        auto-assign: false
        addresses:
        - 72.18.145.240/28