---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: metallb
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: metallb
    version: 0.1.12
  values:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    configInline:
      # bgp-communities:
      #   calico-nomesh: "65001:100"
      peers:
        # core01a
        - peer-address: 172.26.3.2
          peer-asn: 64567
          my-asn: 65001
        # core01b
        - peer-address: 172.26.3.3
          peer-asn: 64567
          my-asn: 65001
      address-pools:
      - name: public
        protocol: bgp
        auto-assign: false
        addresses:
        - 72.18.145.240/28
        # bgp-advertisements:
        # - communities:
        #   - calico-nomesh